#!/bin/bash
#
# @file CypherNotepadLauncher
# @author LeeDongGeon1996
# @date 20.07.02
# @description This script will execute CypherNotepad(2.1)
#
RED='\033[0;31m'
NC='\033[0m' # No Color
java_version=`java -version 2>&1 | grep 'java version' | awk 'NR==1{ gsub(/"/,""); print $3 }'`
if [ -d "/opt/CypherNotepad/runtime" ] && [ -f "/opt/CypherNotepad/CypherNotepad" ]
then
	echo "[Launcher]Cypher Notepad is launched with bundled JRE."
	/opt/CypherNotepad/CypherNotepad
else
	if [ "$java_version" != "" ]
	then
		echo "[Launcher]Cypher Notepad is launched with Java ${java_version} on the system."
		java -jar /opt/CypherNotepad/app/Cypher-Notepad_2.1_release.jar
	else
		echo -e "${RED}[Launcher]Fail to execute Cypher Notepad 2.1${NC}"
		echo "Cypher Notepad requires Java Runtime Environment(JRE). But there isn't any version of JRE(recommend 1.8 or higher)."
		echo "Please re-install Cypher Notepad 2.1 using"
		echo ""
		echo "	wget GITHUB LINK"
		echo "	dpkg -i DOWNLOADED DEB"
		echo ""
	fi
fi
